//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CADP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Design()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int DesignId { get; set; }
        public string DesignName { get; set; }
        public string DesignData { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FabricId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
