//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CADP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabric
    {
        public int FabricId { get; set; }
        public string FabricName { get; set; }
        public string Color { get; set; }
        public string Texture { get; set; }
    }
}
